[package]
name = "anglandia-text-rpg"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license = "BSD-3-Clause"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
console = "0.15.7"
rand = "0.8.5"
serde_json = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
whoami = "1.4.1"
