[package]
name = "anglandia-text-rpg"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license = "BSD-3-Clause"
license-file = "./LICENSE.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
