[health]
hp = 100
hunger = 0

[xp]
combat = 11
fishing = 0
cooking = 0
woodcutting = 0
mining = 0
smithing = 0
thieving = 0

[achievements]
monsters_killed = 0
stronghold_defeated = false
earned_million_gold = false
level_100_reached = false
hacked_the_game = true

[bank]
wallet = 10
account1 = 0
account2 = 0
account3 = 0
account4 = 0

[guild_memberships.fishing]
member = false
member_price = 100

[guild_memberships.cooking]
member = false
member_price = 150

[guild_memberships.woodcutting]
member = false
member_price = 300

[guild_memberships.mining]
member = false
member_price = 500

[guild_memberships.smithing]
member = false
member_price = 1000

[equipment.armor]
name = "Bronze"
price = 200
owns = true
defense = 30
durability = 127
default_durability = 200

[equipment.weapon]
name = "Bronze Sword"
price = 30
owns = true
damage = 20
durability = 64
default_durability = 150

[inventory.bait]
name = "Bait"
price = 1
quantity = 0

[inventory.seeds]
name = "Seeds"
price = 1
quantity = 0

[inventory.furs]
name = "Fur"
price = 5
quantity = 0

[inventory.fish]
name = "Fish"
price = 10
quantity = 0

[inventory.food]
name = "Food"
price = 25
quantity = 0

[inventory.wood]
name = "Wood"
price = 20
quantity = 0

[inventory.ore]
name = "Ore"
price = 30
quantity = 0

[inventory.ingots]
name = "Ingot"
price = 50
quantity = 0

[inventory.potions]
name = "Potion"
price = 20
quantity = 12

[inventory.rubies]
name = "Ruby"
price = 200
quantity = 0

[inventory.magic_scrolls]
name = "Magic Scroll"
price = 50
quantity = 0

[inventory.bones]
name = "Bone"
price = 50
quantity = 9

[inventory.dragon_hides]
name = "Dragon Hide"
price = 200
quantity = 0

[inventory.runic_tablets]
name = "Runic Tablet"
price = 1000
quantity = 0

[armor.leather]
name = "Leather"
price = 50
owns = false
defense = 10
durability = 100
default_durability = 100

[armor.bronze]
name = "Bronze"
price = 200
owns = true
defense = 30
durability = 127
default_durability = 200

[armor.iron]
name = "Iron"
price = 500
owns = false
defense = 50
durability = 300
default_durability = 300

[armor.steel]
name = "Steel"
price = 750
owns = false
defense = 100
durability = 500
default_durability = 500

[armor.dragonhide]
name = "Dragonhide"
price = 1000
owns = false
defense = 200
durability = 500
default_durability = 500

[armor.mystic]
name = "Magic"
price = 10000
owns = false
defense = 1000
durability = 10000
default_durability = 10000

[weapons.wooden_sword]
name = "Wooden Sword"
price = 10
owns = false
damage = 10
durability = 100
default_durability = 100

[weapons.bronze_sword]
name = "Bronze Sword"
price = 30
owns = true
damage = 20
durability = 64
default_durability = 150

[weapons.iron_sword]
name = "Iron Sword"
price = 100
owns = false
damage = 50
durability = 200
default_durability = 200

[weapons.steel_sword]
name = "Steel Rapier"
price = 500
owns = false
damage = 200
durability = 500
default_durability = 500

[weapons.mystic_sword]
name = "Magic Sword"
price = 5000
owns = false
damage = 500
durability = 1000
default_durability = 1000

[weapons.wizard_staff]
name = "Wizard Staff"
price = 10000
owns = false
damage = 1000
durability = 2000
default_durability = 2000

[settings]
username = "admin"
password_hash = "password"
developer = false
locked = false
hardmode = false
