[health]
hp = 100
hunger = 0

[xp]
combat = 0
fishing = 0
cooking = 0
woodcutting = 0
mining = 0
smithing = 0
thieving = 0

[achievements]
monsters_killed = 0
stronghold_defeated = false
earned_million_gold = true
level_100_reached = false
hacked_the_game = true

[bank]
wallet = 749100
account1 = 500
account2 = 0
account3 = 0
account4 = 0

[guilds]
thieving = false
fishing = false
cooking = false
woodcutting = false
mining = false
smithing = false

[equipment]

[items]
bait = 100
seeds = 0
furs = 0
fish = 0
food = 0
wood = 0
ore = 0
ingots = 0
potions = 0
rubies = 0
magic_scrolls = 0
bones = 0
dragon_hides = 0
runic_tablets = 0

[armor.leather]
owns = false
defense = 10
durability = 100
default_durability = 100
equipped = false
flag = "Leather"

[armor.bronze]
owns = false
defense = 30
durability = 200
default_durability = 200
equipped = false
flag = "Bronze"

[armor.iron]
owns = false
defense = 50
durability = 300
default_durability = 300
equipped = false
flag = "Iron"

[armor.steel]
owns = false
defense = 100
durability = 500
default_durability = 500
equipped = false
flag = "Steel"

[armor.dragonhide]
owns = false
defense = 200
durability = 500
default_durability = 500
equipped = false
flag = "Dragonhide"

[armor.mystic]
owns = false
defense = 1000
durability = 10000
default_durability = 10000
equipped = false
flag = "Mystic"

[weapons.wooden_sword]
owns = false
equipped = false
damage = 10
durability = 100
default_durability = 100
flag = "WoodenSword"

[weapons.bronze_sword]
owns = false
equipped = false
damage = 20
durability = 150
default_durability = 150
flag = "BronzeSword"

[weapons.iron_sword]
owns = false
equipped = false
damage = 50
durability = 200
default_durability = 200
flag = "IronSword"

[weapons.steel_sword]
owns = false
equipped = false
damage = 200
durability = 500
default_durability = 500
flag = "SteelSword"

[weapons.mystic_sword]
owns = false
equipped = false
damage = 500
durability = 1000
default_durability = 1000
flag = "MysticSword"

[weapons.wizard_staff]
owns = false
equipped = false
damage = 1000
durability = 2000
default_durability = 2000
flag = "WizardStaff"

[settings]
username = "admin"
password_hash = ""
developer = true
locked = false
hardmode = false
