[health]
hp = 100
hunger = 0

[xp]
combat = 0
fishing = 592
cooking = 80
woodcutting = 25
mining = 0
smithing = 2
thieving = 241

[achievements]
monsters_killed = 0
stronghold_defeated = false
earned_million_gold = false
level_100_reached = false
hacked_the_game = true

[bank]
wallet = 400
account1 = 0
account2 = 0
account3 = 0
account4 = 0

[guilds]
thieving = true
fishing = true
cooking = false
woodcutting = false
mining = false
smithing = false

[equipment]

[items]
bait = 0
seeds = 0
furs = 0
fish = 0
food = 0
wood = 8
ore = 0
ingots = 1
potions = 0
rubies = 0
magic_scrolls = 0
bones = 0
dragon_hides = 0
runic_tablets = 0

[armor.leather]
name = "Leather Armor"
owns = false
defense = 10
durability = 100
default_durability = 100
equipped = false

[armor.bronze]
name = "Bronze Armor"
owns = false
defense = 30
durability = 200
default_durability = 200
equipped = false

[armor.iron]
name = "Iron Armor"
owns = false
defense = 50
durability = 300
default_durability = 300
equipped = false

[armor.steel]
name = "Steel Armor"
owns = false
defense = 100
durability = 500
default_durability = 500
equipped = false

[armor.dragonhide]
name = "Dragonhide Armor"
owns = false
defense = 200
durability = 500
default_durability = 500
equipped = false

[armor.mystic]
name = "Mystic Armor"
owns = false
defense = 1000
durability = 10000
default_durability = 10000
equipped = false

[weapons.wooden_sword]
name = "Wooden Sword"
owns = false
equipped = false
damage = 10
durability = 100
default_durability = 100

[weapons.bronze_sword]
name = "Bronze Sword"
owns = false
equipped = false
damage = 20
durability = 150
default_durability = 150

[weapons.iron_sword]
name = "Iron Sword"
owns = false
equipped = false
damage = 50
durability = 200
default_durability = 200

[weapons.steel_sword]
name = "Steel Rapier"
owns = false
equipped = false
damage = 200
durability = 500
default_durability = 500

[weapons.mystic_sword]
name = "Mystic Sword"
owns = false
equipped = false
damage = 500
durability = 1000
default_durability = 1000

[weapons.wizard_staff]
name = "Wizard Staff"
owns = false
equipped = false
damage = 1000
durability = 2000
default_durability = 2000

[settings]
username = "admin"
password_hash = ""
developer = true
locked = false
hardmode = false
